FROM nginx
ARG PORT=80
ENV PORT=${PORT}

RUN rm /etc/nginx/conf.d/default.conf
COPY docker/nginx.conf /etc/nginx/
RUN mkdir -p /opt/www/amax-explorer
COPY ./frontend/dist/ /opt/www/amax-explorer/
EXPOSE ${PORT}