FROM node:10.15.3

ARG PORT=3039
ENV PORT=${PORT}

WORKDIR /opt/expsvr/server
COPY ./backend .

RUN npm update -g && npm install -g pm2@3.5.1 && npm install -g express && npm install -g install

CMD ["pm2-runtime", "./ecosystem.config.js", "--web"]

EXPOSE ${PORT}